version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=112233
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5678:5432"

  storebackground:
    image: jevgenik/storebackend
    ports:
      - "5000:80"
    depends_on:
      - db
healthcheck:
        test: ["CMD", "ping", "-n", "15", "localhost"]
        interval: 5s
        timeout: 5s
        retries: 1