version: '3.4'

services:
  storebackground:
    image: jevgenik/storebackend
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=112233
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5678:5432"

